---

image: "reporunner/golang-alpine"
checkout_dir: /go/src/github.com/Luzifer/password

commands:
  - make publish

environment:
  CGO_ENABLED: 0
  GHUSER: Luzifer
  PACKAGES: github.com/Luzifer/password/cmd/password
  REPO: password
