---

image: "reporunner/archlinux"
checkout_dir: /go/src/github.com/Luzifer/password

commands:
  - pacman -Sy --noconfirm
      go
      nodejs-lts-gallium
      npm
      zip
  - make compile_js
  - make
      -C cmd/password
      -f ../../Makefile
      publish

environment:
  CGO_ENABLED: 0
  DRAFT: 'false'
  GHUSER: Luzifer
  GOPATH: /go
  PACKAGES: .
  REPO: password
