name: test-and-build
on:
  push: {}

permissions:
  contents: write
  issues: write

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:d5d19c3de13ce299f87c340d3abef643c8064ff6b1328044ea0750497242b0a8
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 'Lint and build frontend'
        run: make frontend_lint frontend_prod

      - name: 'Lint and test code'
        run: |
          go test -cover -v ./...
          golangci-lint run ./...

      - name: Lint and test library
        run: go test -cover -v ./...
        working-directory: lib

      - name: Do a quick local compile
        run: make build
