name: test-and-build
on:
  push: {}

permissions:
  contents: write
  issues: write

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:86d4fdcadcf720372e467a6dfd0361a7013057a7f4b760381f7423e260c4f7cd
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Lint and build frontend'
        run: make frontend_lint frontend_prod

      - name: 'Lint and test code'
        run: |
          go test -cover -v ./...
          golangci-lint run ./...

      - name: Lint and test library
        run: go test -cover -v ./...
        working-directory: lib

      - name: Do a quick local compile
        run: make build
