name: test-and-build
on:
  push: {}

permissions:
  contents: write
  issues: write

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:c43b15d3b949c752834ebf478f0ce5b36b77b16ab31a0295c51964f13adb1e7d
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Lint and build frontend'
        run: make frontend_lint frontend_prod

      - name: 'Lint and test code'
        run: |
          go test -cover -v ./...
          golangci-lint run ./...

      - name: Lint and test library
        run: go test -cover -v ./...
        working-directory: lib

      - name: Do a quick local compile
        run: make build
